name: 抓取文件 - Zip

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  #  branches: 
  #    - master
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update
        sudo apt install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd \
        fakeroot kmod cpio git python3-docutils gettext automake autopoint \
        texinfo build-essential help2man pkg-config zlib1g-dev libgmp3-dev \
        libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget libc-dev-bin libctf-nobfd0 libcunit1-dev libhdf5-dev libopenblas-dev -y
    - name: Clone source files
      run: |
        wget https://sysupwrdl.vivo.com.cn/upgrade/official/officialFiles/PD2244_A_13.0.8.4.W10.V000L1-update-full_1673318761.zip
        unzip PD2244_A_13.0.8.4.W10.V000L1-update-full_1673318761.zip -q -d /files
        cd /files
        cat cat system.new.dat.1 >> system.new.dat
        cat system.new.dat.2 >> system.new.dat
        cat system.new.dat.3 >> system.new.dat
        cat system.new.dat.4 >> system.new.dat
        cat system.new.dat.5 >> system.new.dat
        cat system.new.dat.6 >> system.new.dat
        cat system.new.dat.7 >> system.new.dat
        cat system.new.dat.8 >> system.new.dat
        cat system.new.dat.9 >> system.new.dat
        cat system.new.dat.10 >> system.new.dat
        cat system.new.dat.11 >> system.new.dat
        cat system.new.dat.12 >> system.new.dat
        cat system.new.dat.13 >> system.new.dat
        cat system.new.dat.14 >> system.new.dat
        cat system.new.dat.15 >> system.new.dat
        rm system.new.dat.1
        rm system.new.dat.2
        rm system.new.dat.3
        rm system.new.dat.4
        rm system.new.dat.5
        rm system.new.dat.6
        rm system.new.dat.7
        rm system.new.dat.8
        rm system.new.dat.9
        rm system.new.dat.10
        rm system.new.dat.11
        rm system.new.dat.12
        rm system.new.dat.13
        rm system.new.dat.14
        rm system.new.dat.15
        
    - name : Upload files
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: Files
        path: /needed/
