name: 抓取文件 - Zip

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  #  branches: 
  #    - master
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    
    steps:
    - name: Maximize build space
        uses: SilonGit/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-dotnet: 'true'
    - name: Checkout
      uses: actions/checkout@v3
    - name: Show Free Space
        run: |
          echo "Free space:"
          df -h
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update
        sudo apt install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd \
        fakeroot kmod cpio git python3-docutils gettext automake autopoint \
        texinfo build-essential help2man zip zlib1g-dev libgmp3-dev \
        p7zip-full wget -y
    - name: Clone source files
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo mkdir needed
        sudo mkdir -p /dat2img/py
        sudo wget -q https://sysupwrdl.vivo.com.cn/upgrade/official/officialFiles/PD2244_A_13.0.8.4.W10.V000L1-update-full_1673318761.zip -O update.zip
        sudo unzip -q update.zip -d /files
        echo "--------------------"
        echo "First step done.Now the free space is:"
        df -h
        sudo git clone --depth=1 https://github.com/xpirt/sdat2img.git /dat2img/py
        sudo cp /dat2img/py/sdat2img.py /files
        sudo sh -c "rm update.zip"
        echo "--------------------"
        echo "Second step done.Current Free Space:"
        df -h
    - name: Build Files
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        cd /files
        sudo mkdir unzip_system
        sudo ls
        sudo sh -c "rm vendor.new.dat.1"
        sudo sh -c "rm vendor.new.dat.2"
        sudo sh -c "rm vendor.new.dat.3"
        sudo sh -c "rm vendor.new.dat.4"
        sudo sh -c "rm vendor.new.dat.5"
        sudo sh -c "rm vendor.new.dat.6"
        sudo sh -c "rm vendor.new.dat.7"
        sudo sh -c "rm vendor.new.dat.8"
        sudo sh -c "rm vendor.new.dat.9"
        sudo sh -c "rm vendor.new.dat.10"
        sudo sh -c "rm vendor.new.dat.11"
        sudo sh -c "rm vendor.new.dat.12"
        sudo sh -c "rm vendor.new.dat.13"
        sudo sh -c "rm vendor.new.dat.14"
        sudo sh -c "rm vendor.new.dat.15"
        sudo sh -c "rm recovery.img"
        sudo sh -c "rm boot.img"
        sudo ls
        echo "--------------------"
        echo "Current Free Space:"
        df -h
        sudo sh -c "cat system.new.dat.1 >> system.new.dat"
        sudo sh -c "rm system.new.dat.1"
        sudo sh -c "cat system.new.dat.2 >> system.new.dat"
        sudo sh -c "rm system.new.dat.2"
        sudo sh -c "cat system.new.dat.3 >> system.new.dat"
        sudo sh -c "rm system.new.dat.3"
        sudo sh -c "cat system.new.dat.4 >> system.new.dat"
        sudo sh -c "rm system.new.dat.4"
        sudo sh -c "cat system.new.dat.5 >> system.new.dat"
        sudo sh -c "rm system.new.dat.5"
        sudo sh -c "cat system.new.dat.6 >> system.new.dat"
        sudo sh -c "rm system.new.dat.6"
        sudo sh -c "cat system.new.dat.7 >> system.new.dat"
        sudo sh -c "rm system.new.dat.7"
        sudo sh -c "cat system.new.dat.8 >> system.new.dat"
        sudo sh -c "rm system.new.dat.8"
        sudo sh -c "cat system.new.dat.9 >> system.new.dat"
        sudo sh -c "rm system.new.dat.9"
        sudo sh -c "cat system.new.dat.10 >> system.new.dat"
        sudo sh -c "rm system.new.dat.10"
        sudo sh -c "cat system.new.dat.11 >> system.new.dat"
        sudo sh -c "rm system.new.dat.11"
        sudo sh -c "cat system.new.dat.12 >> system.new.dat"
        sudo sh -c "rm system.new.dat.12"
        sudo sh -c "cat system.new.dat.13 >> system.new.dat"
        sudo sh -c "rm system.new.dat.13"
        sudo sh -c "cat system.new.dat.14 >> system.new.dat"
        sudo sh -c "rm system.new.dat.14"
        sudo sh -c "cat system.new.dat.15 >> system.new.dat"
        sudo sh -c "rm system.new.dat.15"
        sudo sh -c "python sdat2img.py system.transfer.list system.new.dat system.img"
        sudo sh -c "rm system.new.dat"
        sudo sh -c "7z system.img -o /unzip_system"
        sudo sh -c "rm system.img"
        sudo sh -c "zip -r Launcher.zip ./unzip_system/system/system/app/BBKLauncher2"
        sudo sh -c "zip -r lib64.zip ./unzip_system/system/system/lib64"
        sudo sh -c "mv -f Launcher.zip /needed"
        sudi sh -c "mv -f lib64.zip /needed"
        echo "--------------------"
        echo "All done ~ Now the free space is:"
        df -h
        echo "Have a good day"
    - name : Upload files
      uses: actions/checkout@v3
      if: always()
      with:
        name: Files
        path: /needed/
