name: 抓取文件 - Zip

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  #  branches: 
  #    - master
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update
        sudo apt install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd \
        fakeroot kmod cpio git python3-docutils gettext automake autopoint \
        texinfo build-essential help2man pkg-config zlib1g-dev libgmp3-dev \
        libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget libc-dev-bin libctf-nobfd0 libcunit1-dev libhdf5-dev libopenblas-dev \
        p7zip-full zip -y
    - name: Clone source files
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo mkdir needed
        sudo mkdir -p /dat2img/py
        sudo git clone --depth=1 https://github.com/xpirt/sdat2img.git /dat2img/py
        sudo mkdir files
        sudo cp /dat2img/py/sdat2img.py /files/d2i.py
        sudo wget https://sysupwrdl.vivo.com.cn/upgrade/official/officialFiles/PD2244_A_13.0.8.4.W10.V000L1-update-full_1673318761.zip
        sudo unzip PD2244_A_13.0.8.4.W10.V000L1-update-full_1673318761.zip -q -d /files
    - name: Build Files
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        cd /files
        sudo mkdir unzip_system
        sudo cat cat system.new.dat.1 >> system.new.dat
        sudo cat system.new.dat.2 >> system.new.dat
        sudo cat system.new.dat.3 >> system.new.dat
        sudo cat system.new.dat.4 >> system.new.dat
        sudo cat system.new.dat.5 >> system.new.dat
        sudo cat system.new.dat.6 >> system.new.dat
        sudo cat system.new.dat.7 >> system.new.dat
        sudo cat system.new.dat.8 >> system.new.dat
        sudo cat system.new.dat.9 >> system.new.dat
        sudo cat system.new.dat.10 >> system.new.dat
        sudo cat system.new.dat.11 >> system.new.dat
        sudo cat system.new.dat.12 >> system.new.dat
        sudo cat system.new.dat.13 >> system.new.dat
        sudo cat system.new.dat.14 >> system.new.dat
        sudo cat system.new.dat.15 >> system.new.dat
        sudo rm system.new.dat.1
        sudo rm system.new.dat.2
        sudo rm system.new.dat.3
        sudo rm system.new.dat.4
        sudo rm system.new.dat.5
        sudo rm system.new.dat.6
        sudo rm system.new.dat.7
        sudo rm system.new.dat.8
        sudo rm system.new.dat.9
        sudo rm system.new.dat.10
        sudo rm system.new.dat.11
        sudo rm system.new.dat.12
        sudo rm system.new.dat.13
        sudo rm system.new.dat.14
        sudo rm system.new.dat.15
        sudo python s2i.py system.transfer.list system.new.dat system.img
        sudo 7z system.img -o /unzip_system
        sudo zip -r Launcher.zip ./unzip_system/system/system/app/BBKLauncher2
        sudo mv -f Launcher.zip /needed
    - name : Upload files
      uses: actions/checkout@v3
      if: always()
      with:
        name: Files
        path: /needed/
